apiVersion: v1
kind: Secret
metadata:
  name: db-config
  namespace: integration
type: Opaque
stringData:
  db.properties: |
    db.name: EasyFranchiseHANADB
    db.sqlendpoint: 5efb7819-c76f-4f53-b756-94210033a9b9.hana.trial-us10.hanacloud.ondemand.com:443
    db.admin: DBADMIN
    db.password: Present1