apiVersion: v1
kind: Secret
metadata:
  name: db-config
  namespace: integration
type: Opaque
stringData:
  db.properties: |
    db.name: EasyFranchiseHANADB
    db.sqlendpoint: 5efb7819-c76f-4f53-b756-94210033a9b9.hana.trial-us10.hanacloud.ondemand.com:443
    db.admin: DBADMIN
    db.password: Present1
  db.properties-75965dce-a082-4bbf-9c8f-1b59dd11161e: |
    db.name: EasyFranchiseHANADB
    db.sqlendpoint: 5efb7819-c76f-4f53-b756-94210033a9b9.hana.trial-us10.hanacloud.ondemand.com:443
    db.admin: DBADMIN
    db.password: Present1
  db.properties-e3b722a8-1339-46fd-815e-4f6cf782905e: |
    db.name: EasyFranchiseHANADBxxx
    db.sqlendpoint: 5efb7819-c76f-4f53-b756-94210033a9b9xxx.hana.trial-us10.hanacloud.ondemand.com:443
    db.admin: DBADMIN
    db.password: Present1